### ISSUE TITLE
Linux build

### ISSUE THREAD

**Issue by LukasPietzschmann** [Gremmling/Ki_Exponat#1]
Currently, there is only a build for macOS and Windows. Is there any chance you could also provide a Linux build?

Thanks in advance :)

**Comment by Gremmling** [comment]
Yes, I will add it, but I have to admit that I couldn't test the Linux and MacOS build. So there might be some bugs :D

**Comment by LukasPietzschmann** [comment]
> I have to admit that I couldn't test

No worries, I just want to take a quick look at your work. It doesn't matter if there are some bugs :)

**Comment by LukasPietzschmann** [comment]
Small update: it worked like a charm. Thanks a lot for sharing :)
